### ISSUE TITLE
Bug with shinken 2.2 and webui 2.2

### ISSUE THREAD

**Issue by kayk22** [shinken-monitoring/mod-auth-ws-glpi#1]
Here is the warning:
WARNING: [Shinken] Cannot load auth-ws-glpi as a package (No module named auth-ws-glpi.module), trying as module..

**Comment by mohierf** [comment]
I had this problem yesterday on a fresh install ... it is only because there is no **init**.py file in the module directory ! You should copy any other module **init**.py file in the directory ...

 I will commit a version this afternoon
